export default {
  experiences: [
    {
      organization: 'OpenTable',
      title: 'Senior Software Engineer',
      startDate: 'Feb 2019',
      team: 'Consumer Web - Booking Team',
      location: 'San Francisco, CA',
    },
    {
      organization: 'Freelance',
      startDate: 'Dec 2018',
      endDate: 'Feb 2019',
    },
    {
      organization: 'Field Nation',
      title: 'Senior Software Engineer',
      startDate: 'Dec 2017',
      endDate: 'Dec 2018',
      team: 'Platform Team',
      location: 'Minneapolis, MN',
    },
    {
      organization: 'Alley Interactive',
      title: 'Senior Developer',
      startDate: 'July 2014',
      endDate: 'Dec 2017',
      team: 'Data Science (Emerging Technologies) Team',
      location: 'Remote (Minneapolis, MN)',
    },
    {
      organization: 'Walker Arts Center',
      title: 'Front-end Developer',
      startDate: 'Sept 2013',
      endDate: 'July 2014',
      location: 'Minneapolis, MN',
    },
    {
      organization: 'Blue Earth Interactive',
      title: 'Intern',
      team: 'Systems Administration',
      startDate: 'Jul 2013',
      endDate: 'Sept 2013',
      location: 'Saint Paul, MN',
    },
    {
      organization: 'SMCPros',
      title: 'Developer',
      startDate: 'Jan 2013',
      endDate: 'July 2013',
      location: 'Minneapolis, MN',
    },
    {
      organization: 'Freelance',
      startDate: 'Jun 2007',
      endDate: 'July 2014',
    },
    {
      organization: 'Blend Interactive',
      title: 'Intern',
      team: 'Developers',
      startDate: 'May 2012',
      endDate: 'Aug 2012',
      location: 'Sioux Falls, SD',
    },
  ],
  education: [
    {
      organization: 'Dakota State University',
      title: 'Bachelor of Science',
      team: 'Computer & Network Security',
      startDate: 'March 2010',
      endDate: 'Dec 2012',
      location: 'Madison, SD',
    },
  ],
  buzzwords: [
    'Pragmatic Functional Programmer',
    'Development Culture Evangelist',
    'Isomorphic JavaScript Devotee',
    'Autodidact & Sophophile',
  ],
  proficiencies: {
    expert: ['JavaScript (ES6+)', 'ReactJS', 'NodeJS', 'HTML5', 'CSS'],
    advanced: [
      'Functional Programming',
      'TypeScript',
      'GraphQL',
      'MongoDB',
      'jQuery',
      'Redis',
      'Jest',
    ],
    experienced: ['PostgreSQL', 'Python', 'Docker', 'D3.js', 'MySQL', 'AWS'],
    interest: ['Machine Learning', 'Clojure', 'GoLang', 'RXjs'],
    former: ['AngularJS', 'Ember', 'Backbone', 'PHP'],
  },
};
