name: Auto Create PR
on:
  push:
    branches-ignore:
      - 'master'
    tags-ignore:
      - 'dependencies'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    name: pull-request
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: '' # If blank, default: triggered branch
          destination_branch: 'master' # If blank, default: master
          pr_title: 'Pulling ${{ github.ref }} into master' # Title of pull request
          pr_body: ':crown: *An automated PR*' # Full markdown support, requires pr_title to be set
          pr_template: '.github/PULL_REQUEST_TEMPLATE.md' # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: '' # Comma-separated list (no spaces)
          pr_assignee: '' # Comma-separated list (no spaces)
          pr_label: 'auto-pr' # Comma-separated list (no spaces)
          pr_milestone: '' # Milestone name
          pr_draft: true # Creates pull request as draft
          pr_allow_empty: false # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
