name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot auto merge
        uses: fastify/github-action-merge-dependabot@v2.2.0
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          merge-comment: 'Auto-merge dependabot...'
