name: Pull Request Checking
on: pull_request

jobs:
  # Check for new dependencies
  check_new_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: hiwelo/new-dependencies-action@1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  # Proper Language Linting
  language-lint:
    name: Language Linting (via Alex)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: theashraf/alex-action@master
  # Eslint Checker
  eslint:
    name: Eslint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          eslint_flags: '-c .eslintrc src/'
          level: warning
          github: github-pr-check
